name: CF Pages

on:
  push:
    branches:
      - 'md'
  workflow_dispatch:      

jobs:
  
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'config'
          token: ${{ secrets.PERSONAL_TOKEN }}
          submodules: recursive
          fetch-depth: 0
          
      - name: Update submodules
        run: git submodule update --remote --recursive

      - name: Commit & push changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push

      - name: Download theme
        run: |
          mkdir -p themes/blowfish
          git clone --depth 1 https://github.com/0Vessel0/blowfish.git themes/blowfish

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.119.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: public
          publish_dir: ./public
